### ISSUE TITLE
Running a demo

### ISSUE THREAD

**Issue by a5his** [rakannimer/react-google-charts#127]
Version
react-google-charts 1.5.3
react ^15.3.0

Hey, I am not able to run demo after following given instructions. Below is what I am getting.

<img width="833" alt="screen shot 2017-03-24 at 7 34 27 am" src="https://cloud.githubusercontent.com/assets/330362/24277336/942032a2-1064-11e7-90b5-946f60f2c609.png">

<img width="1024" alt="screen shot 2017-03-24 at 12 15 55 am" src="https://cloud.githubusercontent.com/assets/330362/24264012/1f1e82d4-1027-11e7-80c2-cb4adc96f8dd.png">

Thanks

**Comment by RakanNimer** [comment]
How are you running the demo ? 

```
cd demo/ && npm start
```

Should work.

**Comment by a5his** [comment]
@RakanNimer Exactly the same and I am encountering above mentioned error.

**Comment by SiqiTian-minted** [comment]
Same here, exactly followed https://github.com/RakanNimer/react-google-charts#examples, same error.

**Comment by SiqiTian-minted** [comment]
@RakanNimer the unexpected token is JSX, since you are not using `webpack`, I have no idea where the settings are.

**Comment by RakanNimer** [comment]
Will take a look at this soon and update docs or code !

**Comment by SiqiTian-minted** [comment]
Thanks, just tried using `yarn` instead of `npm` according to https://github.com/RakanNimer/react-google-charts/issues/137, but still same error

**Comment by danielbchaves** [comment]
Does is have solution? I have same error and I see that issue is too old already
I tryed as README says (npm) and as issue 137 says, both give me same error

Error in ../src/components/Chart.js
Module parse failed: /tmp/react-google-charts/src/components/Chart.js Unexpected token (379:6)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (379:6)
 @ ./src/App.js 12:13-50

**Comment by rakannimer** [comment]
Fixed in v2. Sorry for the hassle !
