### ISSUE TITLE
React 0.14

### ISSUE THREAD

**Issue by michalzwolinski** [RakanNimer/react-google-charts#13]
```jsx
<Chart chartType="PieChart" options={options} data={data} graph_id={id}/>

Error: Invariant Violation: ReactCompositeComponent.render(): A valid ReactComponent must be returned. You may have returned undefined, an array or some other invalid object.

**Comment by RakanNimer** [comment]
Happy to accept PRs !

**Comment by wladimiiir** [comment]
Is this fixed? Because I still experience the issue.
This warning precedes the Invariant Violation error:
`Warning: Component(...): React component classes must extend React.Component.`

**Comment by evilfer** [comment]
The only problem I'm seeing with this is the dependency "react": "^0.13.3". This locks react to 0.13.x (https://docs.npmjs.com/misc/semver#caret-ranges-1-2-3-0-2-5-0-0-4), so that a project using react 0.14 and react-google-charts ends up with two React versions, apparently this causes the errors above.

Changing the dependency to "react": ">=0.13.3" solves the problem for me.

**Comment by wladimiiir** [comment]
I agree with @evilfer. I have solved the problem the same way and it works fine.

**Comment by pjho** [comment]
:+1: Nice spotting @evilfer,  changing that setting resolves the issue for me as well.

**Comment by RakanNimer** [comment]
@evilfer submitted a pull request to upgrade to React 0.14 and support graph animation when updating.
I updated the package on npm to reflect the newest code (version 0.1.9) .
