### ISSUE TITLE
Rows in Table chart removed on resize

### ISSUE THREAD

**Issue by ymor** [rakannimer/react-google-charts#192]
**Version**

**Tell us which versions you are using:**
react-google-charts 1.5.7
react v16.3.2

**Expected behaviour**
On resize of the browser window the rows of data are still in the table.

**Actual behaviour**
The rows are removed from the DOM.

**Steps to reproduce**
If you run the below fiddle and resize the windows the rows are removed. 
https://jsfiddle.net/Ymorz/ht6unzs3/1/

**Comment by jstralko** [comment]
I'll make a pull request later, but if you remove these lines:

- this.dataTable.removeRows(0, this.dataTable.getNumberOfRows());
- this.dataTable.removeColumns(0, this.dataTable.getNumberOfColumns());

in updateTable on line 176 in file Chart.js. that will fix your issue.

**Comment by ymor** [comment]
Yea I spotted that and redefined the updateDataTable method for now.  Just not sure if removing those 2 lines of code will break anything else :)
Thanks.

**Comment by jstralko** [comment]
It won't break anything because of the line afterward:

`
this.dataTable = buildDataTableFromProps();
`

So it explicitly overwrites the dataTable anyways.  So there is no need to remove rows or columns if the following line will create a new DataTable anyways.

The removeRows and removeColumns just mutates `this.props.data` variable which is bad!

**Comment by rakannimer** [comment]
Should be fixed in v2 !
