### ISSUE TITLE
Failed to set DataTable from data props ! 

### ISSUE THREAD

**Issue by caseyahlan** [rakannimer/react-google-charts#207]
I am getting the error `Failed to set DataTable from data props !`. What causes this? Any insight is appreciated.

**Comment by rakannimer** [comment]
Hey @caseyahlan,

This usually happens if the props you provided to the Chart component are inconsistent or somehow conflicting. Make sure you either provide : 
`data` as a 2 dimensional array OR rows and columns. 

It's very hard to provide more information without seeing your code. 

Can you please provide an example of the code that's throwing this error ?

Here's a [link to a sandbox you can experiment with](https://codesandbox.io/s/6wjj700k9w).

Feel free to re-open this issue with more details !

Cheers !
