### ISSUE TITLE
Using JSON data

### ISSUE THREAD

**Issue by rfaloisio** [rakannimer/react-google-charts#226]
Hi! 

Was looking through the issues and found one that was about using a JSON data to render the chart, but there was no answer to the question.

So, if someone could help me with this.

Thanks in advance!

**Comment by rakannimer** [comment]
Hey @rfaloisio,

Could you give an example of what you're trying to do ? 

I'm not sure I understand.

Cheers

**Comment by rfaloisio** [comment]
Hey @rakannimer 

I'm getting from my db a json in this format:

{ {DateTime: 'xx-xx-xx xx:xx', Number: '5'}, {DateTime: 'xx-xx-xx xx:xx', Number: '7'}, ................ }

And I want to use this json to render the chart. The point is, this format is not being accepted by the wrapper and returns an error.

Could you help me with that?

Thanks!

**Comment by rakannimer** [comment]
So the shape of the data you're receiving is : 
```typescript
Array<{DateTime:string, Number:string}>
```
What you need is to do is to split that data into 2 arrays, 
one that contains the `columns` information 
and one that contains the `rows` information

so in your case we want our columns to be : 
```javascript
const columns = [{ label: "DateTime", type:"date" }, { label: "Number", type:"number" }]
```
and the rows to be : 
```javascript
const rowsWithStringData = [['xx-xx-xx xx:xx', '5'], ['xx-xx-xx xx:xx', '7']]
```

But the data in the rows above won't work because it's provided as strings and we said that our columns are of type `date` and `number` respectively.

So we need to convert 'xx-xx-xx xx:xx' to a Date instance and '5' to a number.

So let's convert the above rows to the right types : 

```javascript
const rows = rowsWithStringData.map((row) => {
	const [stringDate, stringNumber] = row
    return [new Date(Date.parse(stringDate)), parseInt(stringNumber, 10)]
})
```

Now that the columns and rows are in the right format you can render pass them as props.

In your example it would look something like this : 

```javascript
const dataFromDB = [{DateTime: 'xx-xx-xx xx:xx', Number: '5'}, {DateTime: 'xx-xx-xx xx:xx', Number: '7'}]

const columns = [{ label: "DateTime", type:"date" }, { label: "Number", type:"number" }]

const rows = dataFromDB.map(
	(point) => (
		[
			new Date(Date.parse(point.DateTime)),
			parseInt(point.Number, 10)
		]
	)
)

// In your render method return

<Chart
	chartType="PickOne"
	columns={columns}
	rows={rows}
	// otherProps?
/>
```

Hope that helps !

**Comment by rakannimer** [comment]
You can also check https://react-google-charts.com/data-sources/from-api for more detailed examples !

Cheers !
