### ISSUE TITLE
Discrete chars

### ISSUE THREAD

**Issue by carlesnunez** [rakannimer/react-google-charts#255]
Is possible to create an AreaChart on discrete mode?

Like in this example (first chart)
https://jsfiddle.net/Xfx3h/426/

**Comment by rakannimer** [comment]
Hey @carlesnunez ,

Yes this should be relatively straight-forward: Check https://react-google-charts.com/area-chart for some examples.

The difference between a discrete and continuous chart is just in the column type. If you provide numbers or dates then a continuous chart is assumed, otherwise it's a discrete type.
