### ISSUE TITLE
Using material version of charts.

### ISSUE THREAD

**Issue by bIgBV** [RakanNimer/react-google-charts#29]
I'm trying to load the material version of the charts by passing the `chartPackages` prop. For example, if I set `chartPackages` to the following:

    let chartPackages = ['line'];
    ....
    <Chart chartPackages={chartPackages}....

I get the error `google.load` is not a function. 

A few questions:

* Can I load the material version of charts using the library ? As the `chartPackages` prop isn't documented and I found out about it by looking it at the code.
* Can I update the `README.md` file with the props that the componenet *does* accept in order to be some basic level of documentation ?

Cool library, otherwise, thanks!

**Comment by RakanNimer** [comment]
Hello.

I don't think it's possible to use the material version right now with this library. 
I use [Google Charts Wrapper](https://developers.google.com/chart/interactive/docs/drawing_charts#chartwrapper) to be able to handle all kind of Chart types effortless and unfortunately it doesn't support material charts yet.

As for the chartPackages I prefer not to document it now because in the current version of the library as you've noticed, it's not helpful to load other libraries. 

You can just ignore the *hidden* chartPackages props (who defaults to ['corecharts'])  and pass the chartType directly.

As for updating the ```README.md``` Feel free to edit it :) 
I'd be happy to merge any pull request that helps make the library easier to use. 

Cheers

**Comment by Kameshwaran** [comment]
@bIgBV and @RakanNimer It seems the issue was raised because JSAPI wasn't loaded.

Adding jsapi(http://www.google.com/jsapi) will fix this issue.

**Comment by stevesuh** [comment]
@RakanNimer I would also love material support.  Currently I'm trying to hack your code to make it work but it seems material is the future of Google charts.
