### ISSUE TITLE
several charts on the same page

### ISSUE THREAD

**Issue by sirivan79** [RakanNimer/react-google-charts#7]
Hi, 

really interesting wrapper to work with google charts in react. 

I'm just curious. I'm not abe to figure out myself, how I add more charts to the same page. It seems, that the chart only works, when there's only one chart on the page.

/BR

Martin

**Comment by sirivan79** [comment]
Hmm, just figured it. Don't know if it's the right way though. Just added a function, that returned a random string. That string is used as the graph_id. Might be a hack, but it works though. 

again, thank you for the plugin.

BR
Martin

**Comment by RakanNimer** [comment]
Hey !

This was indeed an issue because al the graphs generated had the same id. This was solved with this commit : https://github.com/RakanNimer/react-google-charts/commit/ce0f8b73dba55818cb37b68f380ac2c005a158ed by doing something very similar to what you're doing :) 

Are you sure you have the latest version ?
Cheers !

**Comment by sirivan79** [comment]
I probably missed out on that commit. Thank you for sharing and enlightening me :-).

**Comment by RakanNimer** [comment]
You're very welcome :)
